firebase_web_api_key = "AIzaSyANtUuW_DIJuk2NjiAUZz_0wDx46907Uuk"

[duitku]
merchant_code = "D21863"
api_key = "0c439b43cdf1a6e4826a74a31fecdfe9"

[firebase]
type = "service_account"
project_id = "tom-stt-db"
private_key_id = "48ac8213e407c3dcd8cdeba0d2e3675e2f4d954e"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXAEjTiPYs2s7c\njzmA9JDAAiwxetaoE5anqyY/8Ij4+EaP9X+ncjMyInZanOwYz8VnGdGZc9IAyFy5\njDtCenzCAoSnY11Zj0SM1S6Ok9rhZHoxDI7X+xalJ9vBAPJUSRuDD+/e1tKPk1bZ\nkQt/5Trdj2LcZfxOd2533oZ0tYg+hM+PQf28920UbQ6VQFd1QPSAZPsrjqFjLMAE\ngRw62ykzDnhNVuj+tOFhw3DnbrDJzPCjIW0GO8r+q+PlvbWXkru90bIPs9+GtJmP\n1CQRPsYpk5e8dTUyhwvbg8LDF/yXYknI6wk6X7CyKUiefOU2+xhwVXB26aCHE66E\nurrKi/l5AgMBAAECggEAAesKgcllGyfCZfHZ0KYKqq28YvqE/IiXKtUVPM2w57y7\npLuBHh7owJPIfhktNJl7D/a3f2QFwGXLK744yHzm1c4TYk70Uh1sSP+yQjRlnORa\nWwImVF8HqBxsAbUh3uk41L7glKuU7Cb6fPQHOd4vE75tCpCvFk4VFKe6fIQL0YN4\nYsGkaWI+vSdT7h18tBkuGfd9XcB14flJfb8z6en0tmgjNeqkCqkQaFxEFYkV3/Ab\n4DRnAwbfUH2WoI72Id5RhL9iKUIKJ8y4MnOwcbIQrocx/Sov3WhsC5dceDwPixH3\nUGxdjPCHN9NxJQk57meatqmTcPXa0ezdOuqXXdO2uwKBgQDE5Kz3cA6Qr+4NXY1k\nfdHTcyFBQfJj97SIM2a6QQavshposO2Lup2pOCQ31YK0zbgy0nGdJTgVVMt+S1bB\nLiQOReL80eAL4Vz7VTXDG3oDnP59N9mhKdqfOa61l+XYC5Vks2VWKsux2ACbbTAw\nw2doT5a2fR0t8sJQUU8SPgd/DwKBgQDEVMdndv1tGyKSr6cDFZsKjwEzw9cWFD0v\n9wVE4WxYLm8HI0ygDmXrnc5xQE2lQqi1uTsL3VwqtlxJRG0zMhicOk6tqgIiHBQf\nBZvMAhDn4fQeQEl28fvGkvJmUQKMIsigFSjXGWTl/Spgeek8e7cD13gfInPMl8wr\nYDfBosl+9wKBgFhtw+lVoJUHDsld7PTnNWfcW2EttymCxMgvHcIlFlWujgHbBLUu\n2UR4/Hs/H3cItePNdE15u9iIvuQ3/fzBNlxasvmNYSy0yMfwmzbHjmM1DW87uDiT\nzaaZh4fzcr03Zp9Vmvu6OMXlF1C3F1+vQzAsHqpTQtmyH+dmvTaaOU+tAoGAUZtP\nu1D5bCWQTFqY2C5d4JiqjkLEH5hQCqTp2sS8jTbXzaa9jfYOJU7V5bstyxiXGdoh\nkf/z9IkSeR3pKhOTqTSPSZ5V/qmfL3ncVYMyVcBVAVIFd1yEI/kmqqLXpTo8HFZP\nQIF8sCB4QdvKt+pQm1cvxflDGvKp2gnHg0RP7ucCgYATpurK2Mvp90nx/d+qGK9X\nErSrGfVYeg+NqEPyMjnmrCOur5it4dyDxMbHp0Wl/eMQhLno1IVEbWF7he61zRMJ\nh7a9Hfg+JjXDeEnS6KV6599swv0sTrlarw+EMmZaAHMR1ic7aeN3e48JWI6zgqWq\nMwoNpV//ZpDsfNBnUmMm5Q==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@tom-stt-db.iam.gserviceaccount.com"
client_id = "110676487164977028682"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40tom-stt-db.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[google_oauth]
client_id = "31857061920-d8j7khrk481og9km5dsg83fq9un4kgfo.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://rapat-dev.streamlit.app/"

[cloudinary]
cloud_name = "tomstt"
api_key = "974711872256172"
api_secret = "wNSQZs01GamY0coQ_Nf2OMi1qvA"
